task 1
DaveMSU/afina pull request #1
Opened 2020-09-29 19:16 UTC by DaveMSU

2020-10-04 00:05 UTC, Fen99 commented on src/storage/SimpleLRU.cpp
> +	auto it = _lru_index.find(key);
Везде перед find нужно сначала проверять размер нового элемента. Если он не влезет точно - зачем искать?

2020-10-04 00:05 UTC, Fen99 commented on src/storage/SimpleLRU.cpp
> +	if( !_lru_head )
Вероятно, это assert. Если !_lru_head, то как элемент мог быть найден?

2020-10-04 00:05 UTC, Fen99 commented on src/storage/SimpleLRU.cpp
> +	_cur_size -= (node->key.size() + node->value.size());
Не предусмотрен случай, если в списке вообще 1 элемент

2020-10-04 00:05 UTC, Fen99 commented on src/storage/SimpleLRU.h
>      std::unordered_map<std::string, std::reference_wrapper<lru_node>> _lru_index;
Неверно: ключи храняться дважды - один раз в списке, другой - в unordered_map
Нужный тип:
```
std::(unordered_)map<std::reference_wrapper<const std::string>, std::reference_wrapper<lru_node>>
```

2020-10-04 00:05 UTC, Fen99 commented on src/storage/SimpleLRU.cpp
> +		update( &it->second.get(), value );
Здесь можно установить значение, которому не хватает места

2020-10-04 00:05 UTC, Fen99 commented on src/storage/SimpleLRU.cpp
> +		if( _cur_size > _max_size )
См. выше - это нужно сразу проверить

2020-10-04 00:05 UTC, Fen99 commented on src/storage/SimpleLRU.cpp
> +		push_front( &node );
Не очень понял. push_front, судя по Put вставляет новый узел (ну и там внутри всякие удаления), а это Get... Наверное, нужно просто переместить в начало

2020-10-04 21:39 UTC, Fen99 requested changes

2020-10-04 21:39 UTC, Fen99 commented on src/storage/SimpleLRU.cpp
> +		update( &it->second.get(), value );
Не исправлено. Также нет передвижения в начало - было же обращение

2020-10-04 21:39 UTC, Fen99 commented on src/storage/SimpleLRU.cpp
> +		update( &it->second.get(), value );
Неверно. При таком сценарии на некоторое время размер хранимых объектов превышает _max_size. Нужно сначала освобождать место, а потом делать update.
В этот момент важно: 1) Достаточно освободить только недостающее место: newvalue.size() - curvalue.size(); 2) во время удаления элементов не удалить ноду, в которой будет изменение

2020-10-04 21:39 UTC, Fen99 commented on src/storage/SimpleLRU.cpp
> +			node->next->prev = node->prev;
Здесь не предусмотрен случай, если node = _lru_tail - тогда нужно обновить хвост:
```
// Нужно проверить, т.к. если это новый элемент, хвост двигать не надо
else if (node == _lru_tail)
{
	_lru_tail = _lru_tail->prev;
}
```

Но! Лучше разделить логики вставки элемента и передвижения его в начало очереди. Иначе это черевато данными ошибками. Вставка в начало не требует всей логики этой функции.

2020-10-05 20:21 UTC, merged

2020-10-06 13:33 UTC, blumix commented on src/storage/SimpleLRU.cpp
> +		pop_back();
вот тут можно удалить ноду, которую хотел обновить