Kharazyan_David_hw1_4
DaveMSU/afina pull request #4
Opened 2020-10-07 11:44 UTC by DaveMSU

2020-10-10 17:54 UTC, Fen99 requested changes

2020-10-10 17:54 UTC, Fen99 commented on src/network/mt_blocking/ServerImpl.cpp
> +    worker_count = 0;
socketset.size()

2020-10-10 17:54 UTC, Fen99 commented on src/network/mt_blocking/ServerImpl.cpp
> +
Здесь нужно взять мьютекс sock_manager

2020-10-10 17:54 UTC, Fen99 commented on src/network/mt_blocking/ServerImpl.cpp
> +        command_to_execute.reset();
Зачем очищать уничтожаемые переменные?

2020-10-10 17:54 UTC, Fen99 commented on src/network/mt_blocking/ServerImpl.cpp
> +	std::size_t arg_remains;
= 0; //!!!

2020-10-10 17:54 UTC, Fen99 commented on src/network/mt_blocking/ServerImpl.cpp
> +    		char client_buffer[4096];
= ""; //!!!

2020-10-10 17:54 UTC, Fen99 commented on src/network/mt_blocking/ServerImpl.h
> +    int max_workers, worker_count;
Тоже неинициализированные

2020-10-12 14:08 UTC, blumix requested changes

2020-10-12 14:08 UTC, blumix commented on src/network/mt_blocking/ServerImpl.cpp
> +        close(client_socket);
close всё ещё может сломать другой поток

2020-10-12 14:08 UTC, blumix commented on src/network/mt_blocking/ServerImpl.cpp
> +		std::unique_lock<std::mutex> lock(sock_manager);
если в этот момент будет вызвана и отработает метод Stop () , то ты добавишь у вже останавливающийся сервер новый поток, который не знает, что ему нудно прекращать работу.

2020-10-16 11:01 UTC, merged